name: medical_appointments
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  font_awesome_flutter: ^9.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Secci칩n de assets donde agregamos la imagen hero-banner.png
  assets:
    - assets/hero-banner.png

  # Puedes a침adir m치s im치genes si las necesitas en el futuro
  # assets:
  #   - assets/other_image.png
